### ISSUE TITLE
OverflowError when running updown.py

### ISSUE THREAD

**Issue by serbinsh** [dropbox/dropbox-sdk-python#158]
Hello

I am attempting to upload files of ~ 9-10 GBs to my dropbox space (where I have ~1.5 TBs free).  I am running into this error

```
[sserbin@modex tviskari_full]$ python2.7 updown.py
Dropbox folder name: ED2_Output_for_Toni
Local directory: to_upload
Total elapsed time for list_folder: 0.437
Descending into  ...
Upload workflow.R? [Y/n] y
Total elapsed time for upload 5079 bytes: 1.002
uploaded as workflow.R
[sserbin@modex tviskari_full]$ mv NPPLE.tar.gz to_upload/
[sserbin@modex tviskari_full]$ python2.7 updown.py
Dropbox folder name: ED2_Output_for_Toni
Local directory: to_upload
Total elapsed time for list_folder: 0.467
Descending into  ...
workflow.R is already synced [stats match]
Upload NPPLE.tar.gz? [Y/n] y
Total elapsed time for upload 9353815493 bytes: 19.211
Traceback (most recent call last):
  File "updown.py", line 237, in <module>
    main()
  File "updown.py", line 105, in main
    upload(dbx, fullname, folder, subfolder, name)
  File "updown.py", line 179, in upload
    mute=True)
  File "/data/software/python/2.7.14/lib/python2.7/site-packages/dropbox-0.0.0-py2.7.egg/dropbox/base.py", line 2144, in files_upload
    f,
  File "/data/software/python/2.7.14/lib/python2.7/site-packages/dropbox-0.0.0-py2.7.egg/dropbox/dropbox.py", line 274, in request
    timeout=timeout)
  File "/data/software/python/2.7.14/lib/python2.7/site-packages/dropbox-0.0.0-py2.7.egg/dropbox/dropbox.py", line 365, in request_json_string_with_retry
    timeout=timeout)
  File "/data/software/python/2.7.14/lib/python2.7/site-packages/dropbox-0.0.0-py2.7.egg/dropbox/dropbox.py", line 449, in request_json_string
    timeout=timeout,
  File "/data/software/python/2.7.14/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/data/software/python/2.7.14/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/software/python/2.7.14/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/data/software/python/2.7.14/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/data/software/python/2.7.14/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/data/software/python/2.7.14/lib/python2.7/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/data/software/python/2.7.14/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/data/software/python/2.7.14/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/data/software/python/2.7.14/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/data/software/python/2.7.14/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/data/software/python/2.7.14/lib/python2.7/httplib.py", line 858, in send
    self.sock.sendall(data)
  File "/data/software/python/2.7.14/lib/python2.7/ssl.py", line 753, in sendall
    v = self.send(data[count:])
  File "/data/software/python/2.7.14/lib/python2.7/ssl.py", line 719, in send
    v = self._sslobj.write(data)
OverflowError: string longer than 2147483647 bytes
[sserbin@modex tviskari_full]$
```
I was however able to run the command for small files.  Is there a file size limit with this?  I thought it was 350GBs for the API?  

Though the error *seems* like it is complaining about the file/folder names?

**Comment by serbinsh** [comment]
Hang on, actually maybe it is a single file size limit, looking again at the error.   Is there an option to change the file size limit, if that is the issue, with the python API?

**Comment by serbinsh** [comment]
Or perhaps strange use of error messages and actually its complaining that the upload will take too long?

**Comment by greg-db** [comment]
Apologies for the confusion! The Dropbox API does support uploading files up to 350 GB in size. 

The updown example itself was not written to support that though. It only uses [the basic `files_upload` method](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.files_upload), but for files larger than 150 MB you need to use upload sessions instead, via the methods [`files_upload_session_start`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.files_upload_session_start), [`files_upload_session_append_v2`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.files_upload_session_append_v2), and [`files_upload_session_finish`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.files_upload_session_finish). I have [a minimal example of using that in this thread](https://www.dropboxforum.com/t5/API-Support-Feedback/python-upload-big-file-example/m-p/166627/highlight/true#M6013).

In that example, I send only 4 MB per request. You can use a larger size, but you shouldn't try to send more than 150 MB per request. Attempting to do so will fail, such as with the error you posted here. (That in particular seems to be a limit in the underlying networking code, but that large of a request would fail if it was sent anyway.)
