### ISSUE TITLE
UnicodeDecodeError in dropbox status command line with export LC_ALL=C

### ISSUE THREAD

**Issue by el-teedee** [dropbox/dropbox-sdk-python#164]
Ubuntu + CLI user here.

Having strange issue with command "dropbox status" and LC_ALL variable.

By default, my terminal is in French, and I get no error :
```
~$ dropbox status ;
À jour
```

Some context:
```
~$ echo $LANG
fr_FR.UTF-8
~$ echo $LC_ALL

~$ dropbox version
Dropbox daemon version: 71.4.108
Dropbox command-line interface version: 2019.02.14
```

When overriding LC_ALL=C to get my terminal in English rather than in French (https://unix.stackexchange.com/a/87748/168003), I get errors (and I reproduce this error when repeating same steps in new terminals).

```
~$ export LC_ALL=C ;
~$ dropbox status ;
Traceback (most recent call last):
  File "/usr/bin/dropbox", line 1594, in <module>
    ret = main(sys.argv)
  File "/usr/bin/dropbox", line 1583, in main
    result = commands[argv[i]](argv[i+1:])
  File "/usr/bin/dropbox", line 743, in newmeth
    return meth(*n, **kw)
  File "/usr/bin/dropbox", line 1215, in status
    lines = dc.get_dropbox_status()['status']
  File "/usr/bin/dropbox", line 714, in __spec_command
    return self.send_command(str(name), kw)
  File "/usr/bin/dropbox", line 672, in send_command
    ok = self.__readline() == "ok"
  File "/usr/bin/dropbox", line 646, in __readline
    toret = self.f.readline().rstrip("\n")
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)
```
And when I restore, it outputs in French with no error:
```
~$ export LC_ALL= ;
~$ dropbox status
À jour
```

**Comment by el-teedee** [comment]
humm, just saw that it is Python sdk project here :/
