### ISSUE TITLE
Catch an exception

### ISSUE THREAD

**Issue by dslackw** [dropbox/dropbox-sdk-python#177]
Hi,

I wonder if there is a way to catch an exception like this:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "main.py", line 145, in checkLoad
    self.connect_to_account()
  File "main.py", line 408, in connect_to_account
    self.connect(self.app_key)
  File "/usr/lib64/python3.7/site-packages/dropbox_filemanager/client.py", line 20, in connect
    self.dbx.users_get_current_account()
  File "/usr/lib64/python3.7/site-packages/dropbox/base.py", line 4508, in users_get_current_account
    None,
  File "/usr/lib64/python3.7/site-packages/dropbox/dropbox.py", line 274, in request
    timeout=timeout)
  File "/usr/lib64/python3.7/site-packages/dropbox/dropbox.py", line 365, in request_json_string_with_retry
    timeout=timeout)
  File "/usr/lib64/python3.7/site-packages/dropbox/dropbox.py", line 456, in request_json_string
    raise BadInputError(request_id, r.text)
dropbox.exceptions.BadInputError: BadInputError('835203ce1bdea136f7668a5ae503c5cc', 'Error in call to API function "users/get_current_account": The given OAuth 2 access token is malformed.')
```

I have tried with the normal ways but I couldn't

Thanks

**Comment by greg-db** [comment]
Yes, you can catch this [`BadInputError`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/exceptions.html#dropbox.exceptions.BadInputError) using `except`. Any of these work, in decreasing order of specificity for the [`BadInputError`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/exceptions.html#dropbox.exceptions.BadInputError) type.

```
try:
    print(dbx.users_get_current_account())
except dropbox.exceptions.BadInputError as e:
    print("Caught BadInputError")
    print(e)
except dropbox.exceptions.HttpError as e:
    print("Caught HttpError")
    print(e)
except dropbox.exceptions.DropboxException as e:
    print("Caught DropboxException")
    print(e)
except Exception as e:
    print("Caught Exception")
    print(e)
```

**Comment by dslackw** [comment]
Thank you @greg-db, it's work fine!
