### ISSUE TITLE
Add support for file id

### ISSUE THREAD

**Issue by joshma** [dropbox/dropbox-sdk-python#29]
I'm guessing the SDK needs to be updated to support fileIds:
```
>>> dbx.files_download('id:YYYYYYYYYYY')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/lib/python2.7/site-packages/dropbox/base.py", line 200, in files_download
    rev)
  File "/path/to/lib/python2.7/site-packages/dropbox/files.py", line 1623, in __init__
    self.path = path
  File "/path/to/lib/python2.7/site-packages/dropbox/files.py", line 1641, in path
    val = self._path_validator.validate(val)
  File "/path/to/lib/python2.7/site-packages/dropbox/babel_validators.py", line 296, in validate
    % (val, self.pattern))
dropbox.babel_validators.ValidationError: 'id:YYYYYYYYYYY' did not match pattern '/.*'
```

**Comment by braincore** [comment]
Yes, it does :) A new release is coming shortly.

**Comment by joshma** [comment]
@braincore awesome thanks! ...how shortly? If we're doing something with it this week, should we hold off for a few more days? I guess we can use the HTTP API for now.

**Comment by braincore** [comment]
Version 3.39 of the SDK available on Github and PyPI has ID support for `files_download`. Happy coding!

**Comment by joshma** [comment]
awesome, great timing haha

**Comment by joshma** [comment]
@braincore any chance `files/list_folder` is planned to accept folder ids? currently getting "malformed_path" errors
