### ISSUE TITLE
Bad Request for url: https://www.dropbox.com/1/oauth2/token

### ISSUE THREAD

**Issue by andyCapone** [dropbox/dropbox-sdk-python#33]
After issue #31 was solved, I get the following error when running the [example-code](http://dropbox-sdk-python.readthedocs.org/en/master/moduledoc.html#dropbox.oauth.DropboxOAuth2FlowNoRedirect) from the docs with version 3.42:

    Traceback (most recent call last):
      File "test.py", line 15, in <module>
        access_token, user_id = auth_flow.finish(auth_code)
      File "/usr/local/lib/python2.7/dist-packages/dropbox/oauth.py", line 178, in finish
        return self._finish(code, None)
      File "/usr/local/lib/python2.7/dist-packages/dropbox/oauth.py", line 60, in _finish
        resp.raise_for_status()
      File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 837, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    HTTPError: 400 Client Error: Bad Request for url: https://www.dropbox.com/1/oauth2/token

**Comment by andyCapone** [comment]
After re-creating the Dropbox-App the error was gone. Sorry if I took anyone's time!!

**Comment by dalanmiller** [comment]
But you shouldn't have to recreate!

**Comment by ianzimmerman** [comment]
I'm also getting this error and recreating the app has not helped. 
`127.0.0.1 - - [18/Nov/2016 16:14:02] "GET /dropbox?state=GG7ZbDv1eCWHvCoq67QPLQ%3D%3D&code=ptPc465Jz2sAAAAAAAACYE6dktBSsF_F2u0hQcJz4JM HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/i/.pyenv/versions/3.4.5/lib/python3.4/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/i/.pyenv/versions/3.4.5/lib/python3.4/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/i/.pyenv/versions/3.4.5/lib/python3.4/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/i/.pyenv/versions/3.4.5/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/i/.pyenv/versions/3.4.5/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/i/.pyenv/versions/3.4.5/lib/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/i/.pyenv/versions/3.4.5/lib/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/i/.pyenv/versions/3.4.5/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/i/.pyenv/versions/3.4.5/lib/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/i/.pyenv/versions/3.4.5/lib/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/i/blueprints/dropbox/controllers.py", line 23, in auth
    result = get_dropbox_auth_flow(session).finish(request.args)
  File "/Users/i/.pyenv/versions/3.4.5/lib/python3.4/site-packages/dropbox/oauth.py", line 425, in finish
    no_redirect_result = self._finish(code, self.redirect_uri)
  File "/Users/i/.pyenv/versions/3.4.5/lib/python3.4/site-packages/dropbox/oauth.py", line 122, in _finish
    resp.raise_for_status()
  File "/Users/i/.pyenv/versions/3.4.5/lib/python3.4/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.dropbox.com/1/oauth2/token`

**Comment by greg-db** [comment]
Can you share the code that results in this? A 400 from this endpoint can indicate an invalid or expired authorization code, for example.

**Comment by ianzimmerman** [comment]
`
@dropbox.route('', methods=['GET'])
def auth():
	
	auth_url = None
	
	def get_dropbox_auth_flow(web_session):
		redirect_uri = request.url
		return DropboxOAuth2Flow(
			current_app.config['DROPBOX_APP_KEY'], current_app.config['DROPBOX_APP_SECRET'], redirect_uri, web_session, 'csrf_token_session_key')
	
	if request.args:
		print(request.args)
		try:
			result = get_dropbox_auth_flow(session).finish(request.args)
			print(result)			
			
			current_user.dropbox_token = result[0]
			
			db_commit()
			return redirect(url_for('.auth'))
			
		except Exception as e:
			raise
	else:
		auth_url = get_dropbox_auth_flow(session).start()
	
	return render_template('dropbox/auth.html', auth_url=auth_url)
`

**Comment by greg-db** [comment]
Thanks! I suspect the issue is with your redirect URI value. Can you share the values of `redirect_uri` and `request.args`?

**Comment by ianzimmerman** [comment]
`
redirect_uri (development): http://localhost:8088/dropbox
`
`
request.args: ImmutableMultiDict([('code', 'ptPc465Jz2sAAAAAAAACYR7QyM0HZ2OmuoWSoCgsZoM'), ('state', 'fTpJDcfDJS4YRzTLd-HBIw==')])
`

**Comment by ianzimmerman** [comment]
I see where you are going, I will change redirect_uri to request.base_url, it is changing on response.

**Comment by greg-db** [comment]
Yes, in addition to being pre-registered on https://www.dropbox.com/developers/apps, the redirect URI needs to be exactly the same across the /authorize URL and the /token call (made in the `finish` method).

**Comment by ianzimmerman** [comment]
That was it, thank you.

**Comment by all3nT** [comment]
I am having the same issue with getting a 400 error. I checked and my urls are the same.

The redirect url is added exactly the same in the api console.
Redirect Url
'redirect_uri': 'http://localhost:8888/dropboxAuth'
Parameters I am receiving from Dropbox on the initial call 
{'state': 'vWcw6LIbqTIU_XwtIsHKDg==', 'code': 'HCGtJ8-I1agAAAAAAAAHM4FZ2Q-kfOb0aoXvo9Ct3oo'}

Here are the request params being sent to https://api.dropboxapi.com/oauth2/token
{'grant_type': 'authorization_code', 'code': 'HCGtJ8-I1agAAAAAAAAHM4FZ2Q-kfOb0aoXvo9Ct3oo', 'client_id': '**********', 'client_secret': '*********', 'redirect_uri': 'http://localhost:8888/dropboxAuth'}

raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.dropboxapi.com/oauth2/token

During handling of the above exception, another exception occurred:

Can you point me in the right direction?

**Comment by greg-db** [comment]
@all3nT Can you share the response body itself? It should contain a more useful error. E.g.: `print(e.message)` or `print(e.response.text)`.

**Comment by all3nT** [comment]
I gave it a try again today after changing nothing and it seems to be working now.
