### ISSUE TITLE
No proxy support for DropboxOAuth2FlowNoRedirect.finish()

### ISSUE THREAD

**Issue by narenchoudhary** [dropbox/dropbox-sdk-python#65]
SDK version 6.3.0

I'm not able to generate access_token behind proxy. `finish()` call on `DropboxOAuth2FlowNoRedirect` instance fails behind HTTP/HTTPS proxy. Since requests are handled by [urllib3](http://urllib3.readthedocs.io/en/latest/managers.html#proxymanager), it'll be really helpful if proxy argument is added to `DropboxOAuth2FlowBase.finish()`.

Setting `HTTP_PROXY` or `HTTP_PROXY` environment variables also isn't working for me.

Here's the error traceback:

```
Enter the authorization code here: abcxyz

Traceback (most recent call last):
    File "start_auth.py", line 40, in <module>
        generate_token(app_key, app_secret)
    File "start_auth.py", line 24, in generate_token
        access_token, user_id = flow.finish(code)
    File "/usr/local/lib/python2.7/dist-packages/dropbox/client.py", line 1404, in finish
        return self._finish(code, None)
    File "/usr/local/lib/python2.7/dist-packages/dropbox/client.py", line 1271, in _finish
        response = self.rest_client.POST(url, params=params)
    File "/usr/local/lib/python2.7/dist-packages/dropbox/rest.py", line 322, in POST
        return cls.IMPL.POST(*n, **kw)
    File "/usr/local/lib/python2.7/dist-packages/dropbox/rest.py", line 260, in POST
        is_json_request=is_json_request)
    File "/usr/local/lib/python2.7/dist-packages/dropbox/rest.py", line 226, in request
        preload_content=False
    File "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 165, in urlopen
        response = conn.urlopen(method, u.request_uri, **kw)
    File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 656, in urlopen
        release_conn=release_conn, **response_kw)
    File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 281, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.dropbox.com', 
port=443): Max retries exceeded with url: /1/oauth2/token (Caused by NewConnectionError 
('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc6ec214ed0>: Failed to 
establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

Thanks in advance.

**Comment by connorworley** [comment]
I think these environment variables should be supported now?

**Comment by connorworley** [comment]
I've confirmed that the HTTPS_PROXY varialbe is respected in oauth flows and other API calls.
