### ISSUE TITLE
DropboxSession has no attribute 'key'

### ISSUE THREAD

**Issue by kratos83** [dropbox/dropbox-sdk-python#66]
Good morning , Dropbox marks this mistake

Traceback (most recent call last):
  File "dialogo.py", line 70, in connessione_dropbox
    accesso = sessione.obtain_access_token(sessione)
  File "/usr/lib/python3.4/site-packages/dropbox/session.py", line 213, in obtain_access_token
    headers, params = self.build_access_headers('POST', url, request_token=request_token)
  File "/usr/lib/python3.4/site-packages/dropbox/session.py", line 249, in build_access_headers
    oauth_params['oauth_token'] = request_token.key
AttributeError: 'DropboxSession' object has no attribute 'key'

Thanks.

**Comment by greg-db** [comment]
You're passing your `DropboxSession` object back into the `obtain_access_token` method, which expects a request token.

In any case, we recommend using OAuth 2 instead, as shown here:

https://www.dropbox.com/developers-v1/core/start/python
