### ISSUE TITLE
Internal server error while uploading files

### ISSUE THREAD

**Issue by anishathalye** [dropbox/dropbox-sdk-python#7]
When I call `files_upload()` a bunch of times, sometimes I get an internal server error. (Retrying usually solves the problem).

What's the reason for this?

If it's some form of rate limiting, would a 4xx error be more appropriate?

**Comment by braincore** [comment]
A rate limit error is a 429 status code and raises a `RateLimitError` exception in the SDK. I'm guessing you were calling `files_upload()` during some server-side instability. At approximately what rate were you making these uploads? Do you have a script for reproducing this?

**Comment by anishathalye** [comment]
This is a kinda weird example, but it seems to get the job done:

```
#!/usr/bin/env python3

import dropbox
import random
import multiprocessing.pool

token = 'YOUR_TOKEN_HERE'

def upload_random(data):
    dbx = dropbox.Dropbox(token)
    mode = dropbox.files.WriteMode('overwrite')
    dbx.files_upload(data, '/tmp/%s' % data, mode)
    print('uploaded %s' % data)

while True:
    pool = multiprocessing.pool.ThreadPool(processes=20)
    data = [str(random.random()) for i in range(1000)]
    pool.map(upload_random, data)
```

Output:

```
... <snip> ...
uploaded 0.6593487886100889
uploaded 0.8371689720398932
uploaded 0.5791303171210294
uploaded 0.7088054144939461
uploaded 0.5961792347613669
uploaded 0.17493724296808022
uploaded 0.07599684817839003
Traceback (most recent call last):
  File "./test.py", line 18, in <module>
    pool.map(upload_random, data)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "./test.py", line 12, in upload_random
    dbx.files_upload(data, '/tmp/%s' % data, mode)
  File "/Users/anish/src/dbx-upload-test/dropbox/base.py", line 323, in files_upload
    f)
  File "/Users/anish/src/dbx-upload-test/dropbox/dropbox.py", line 178, in request
    request_binary)
  File "/Users/anish/src/dbx-upload-test/dropbox/dropbox.py", line 254, in request_json_string_with_retry
    request_binary)
  File "/Users/anish/src/dbx-upload-test/dropbox/dropbox.py", line 317, in request_json_string
    raise InternalServerError(r.status_code, r.text)
dropbox.exceptions.InternalServerError: (500, '')
```

**Comment by braincore** [comment]
Thanks for the repro script! We've found the underlying issue and are working on a fix.

**Comment by braincore** [comment]
Thanks again for the repro script. We've fixed the issue on our server so there's no need for an SDK update.
