### ISSUE TITLE
Error msg in new version for file upload

### ISSUE THREAD

**Issue by BjornFJohansson** [dropbox/dropbox-sdk-python#76]
The new version broke my upload script. I have somethin I copied out of the examples:

```
        rempth = FOLDERLOCATION.joinpath(FOLDERNAME, npth)
        print("uploading", npth, "to", rempth)
        print()
        with npth.open('rb') as f:
            try:
                dbx.files_upload(f, 
                                 str(rempth), 
                                 mode=dropbox.files.WriteMode('overwrite'))
            except dropbox.exceptions.ApiError as err:
                if (err.error.is_path() and
                        err.error.get_path().error.is_insufficient_space()):
                    sys.exit("ERROR: Cannot back up; insufficient space.")
                elif err.user_message_text:
                    print(err.user_message_text)
                    sys.exit()
                else:
                    print(err)
                    sys.exit()
```

```
Traceback (most recent call last):
  File ".continuous_integration/convert_and_send.py", line 177, in <module>
    mode=dropbox.files.WriteMode('overwrite'))
  File "/home/bjorn/anaconda3/envs/bjorn3/lib/python3.5/site-packages/dropbox/base.py", line 1225, in files_upload
    f,
  File "/home/bjorn/anaconda3/envs/bjorn3/lib/python3.5/site-packages/dropbox/dropbox.py", line 249, in request
    timeout=timeout)
  File "/home/bjorn/anaconda3/envs/bjorn3/lib/python3.5/site-packages/dropbox/dropbox.py", line 341, in request_json_string_with_retry
    timeout=timeout)
  File "/home/bjorn/anaconda3/envs/bjorn3/lib/python3.5/site-packages/dropbox/dropbox.py", line 385, in request_json_string
    type(request_binary))
TypeError: expected request_binary as binary type, got <class '_io.BufferedReader'>

```

**Comment by greg-db** [comment]
There are some breaking changes in the latest major release, v7.x. You can find the information here:

https://github.com/dropbox/dropbox-sdk-python/releases/tag/v7.1.0

**Comment by BjornFJohansson** [comment]
ok, thanks
