### ISSUE TITLE
Installer broken with Python3

### ISSUE THREAD

**Issue by timsavage** [dropbox/dropbox-sdk-python#8]
The latest release 3.12 has broken the package when installing with Python 3.4

    pip install dropbox
    Downloading/unpacking dropbox
      Downloading dropbox-3.12.tar.gz (107kB): 107kB downloaded
      Running setup.py (path:/home/tims/.virtualenvs/testp3/build/dropbox/setup.py) egg_info for package dropbox
        Traceback (most recent call last):
          File "<string>", line 17, in <module>
          File "/home/tims/.virtualenvs/testp3/build/dropbox/setup.py", line 4, in <module>
            from ez_setup import use_setuptools
        ImportError: No module named 'ez_setup'
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):

      File "<string>", line 17, in <module>

      File "/home/tims/.virtualenvs/testp3/build/dropbox/setup.py", line 4, in <module>

        from ez_setup import use_setuptools

    ImportError: No module named 'ez_setup'

Was picked up by our CI server.

**Comment by braincore** [comment]
Thanks for the note. I've repro-ed this and will be investigating tomorrow. For now, please pip install an older version.

**Comment by smarx** [comment]
I'm pretty sure this has been fixed.
